komodo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  back_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_RR_Wheel_joint
    pid: {p: 1.0, i: 0.00, d: 0}
  back_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_RL_Wheel_joint
    pid: {p: 1.0, i: 0.00, d: 0}
  front_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_FR_Wheel_joint
    pid: {p: 0.0, i: 0.00, d: 0}
  front_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_FL_Wheel_joint
    pid: {p: 0.0, i: 0.00, d: 0}
  base_rotation_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_base_rotation_joint
    pid: {p: 500.0, i: 0.00, d: 0}
  shoulder_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_shoulder_joint
    pid: {p: 500.0, i: 0, d: 0.0}
  elbow1_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_elbow1_joint
    pid: {p: 700.0, i: 0, d: 0.0}
  elbow2_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_elbow2_joint
    pid: {p: 700.0, i: 0, d: 0.0}
  wrist_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_wrist_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_left_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_right_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  elevator_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_elevator_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}

